version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db.migration:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
